name: Package Armvirt as OpenWrt
on:
  push:
    branches:
      - main
jobs:
  download:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get latest tag name
        id: get_tag_name
        run: echo ::set-output name=tag_name::$(git describe --tags --abbrev=0)
        
      - name: Download Latest Release Asset
        uses: dawidd6/action-download-artifact@v2
        with:
          url: https://github.com/Unwillingx/OpenWrt-N1-firmware/releases/download/${{ steps.get_tag_name.outputs.tag_name }}/file.zip
          path: /opt/openwrt-armvirt-64-default-rootfs.tar.gz
          
      - name: Package Armvirt as OpenWrt
        uses: unifreq/openwrt_packit@master
        env:
          OPENWRT_ARMVIRT: opt/openwrt-armvirt-64-default-rootfs.tar.gz
          PACKAGE_SOC: s905d
          KERNEL_VERSION_DIR: kernel_n1
          KERNEL_VERSION_NAME: 6.1.21
          GH_TOKEN: ${{ secrets.MANAGE_RELEASE }}
      
      - name: Generate release tag
        id: tag
        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
        run: |
          echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
          echo "status=success" >> $GITHUB_OUTPUT
          
      - name: Upload firmware to release
        uses: softprops/action-gh-release@v1
        if: steps.tag.outputs.status == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.MANAGE_RELEASE }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: release.txt
          files: ${{ env.PACKAGED_OUTPUTPATH }}/*
          
          
      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.MANAGE_RELEASE }}
